openapi: "3.0.3"
info:
  title: Sample API
  version: "0.1.0"
servers:
  - url: http://localhost:8080
components:
  schemas:
    user:
      type: object
      description: ユーザー
      required:
        - code
        - id
        - email
        - password
      properties:
        code:
          type: string
          description: ユーザーコード
          example: 6c84fb90-12c4-11e1-840d-7b25c5ee775a
        id:
          type: string
          description: ユーザーID
          example: dummy-user
        email:
          type: string
          description: メールアドレス
          example: dummy-user@gmail.com
        password:
          type: string
          description: パスワード
          example: # TODO
paths:
  /:
    description: ヘルスチェック
    get:
      summary: ヘルスチェック
      responses:
        "200":
          description: ヘルスOK
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: ok
  /users:
    description: ユーザーリスト
    get:
      summary: ユーザーリストを取得します
      description: |
        登録されているすべてのユーザー情報を取得します。
      responses:
        "200":
          description: ユーザーリスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
